### ISSUE TITLE
I found app_transcoder compile error on asterisk 11.6

### ISSUE THREAD

**Issue by akong77** [marcelloceschia/app_transcoder#1]
My system is centos 5.9.And asterisk 11.6 with ffmpeg SVN-r26402
When I compile app_transcoder to asterisk 11.6.
It's will got error message.

```
make[1]: Leaving directory `/root/asterisk-11.6.0/menuselect'
   [CC] app_transcoder.c -> app_transcoder.o
app_transcoder.c: In function 'SendH263VideoFrame':
app_transcoder.c:169: warning: unused variable 'astFormat'
app_transcoder.c:168: warning: unused variable 'size'
app_transcoder.c: In function 'VideoTranscoderSetResize':
app_transcoder.c:520: warning: 'sws_getContext' is deprecated (declared at /usr/local/include/libswscale/swscale.h:194)
app_transcoder.c: In function 'VideoTranscoderCreate':
app_transcoder.c:722: error: 'AVDictionary' undeclared (first use in this function)
app_transcoder.c:722: error: (Each undeclared identifier is reported only once
app_transcoder.c:722: error: for each function it appears in.)
app_transcoder.c:722: error: 'options' undeclared (first use in this function)
app_transcoder.c:921: warning: implicit declaration of function 'avcodec_open2'
app_transcoder.c: In function 'rfc2190_append':
app_transcoder.c:1048: warning: dereferencing type-punned pointer will break strict-aliasing rules
app_transcoder.c: In function 'rfc2429_append':
app_transcoder.c:1100: warning: unused variable 'pebit'
app_transcoder.c: In function 'app_transcode':
app_transcoder.c:1509: warning: enumeration value 'AST_FORMAT_G723_1' not handled in switch
app_transcoder.c:1509: warning: enumeration value 'AST_FORMAT_GSM' not handled in switch
app_transcoder.c:1509: warning: enumeration value 'AST_FORMAT_ULAW' not handled in switch
app_transcoder.c:1509: warning: enumeration value 'AST_FORMAT_ALAW' not handled in switch
app_transcoder.c:1509: warning: enumeration value 'AST_FORMAT_G726_AAL2' not handled in switch
app_transcoder.c:1509: warning: enumeration value 'AST_FORMAT_ADPCM' not handled in switch
app_transcoder.c:1509: warning: enumeration value 'AST_FORMAT_LPC10' not handled in switch
app_transcoder.c:1509: warning: enumeration value 'AST_FORMAT_G729A' not handled in switch
app_transcoder.c:1509: warning: enumeration value 'AST_FORMAT_SPEEX' not handled in switch
app_transcoder.c:1509: warning: enumeration value 'AST_FORMAT_ILBC' not handled in switch
app_transcoder.c:1509: warning: enumeration value 'AST_FORMAT_G726' not handled in switch
app_transcoder.c:1509: warning: enumeration value 'AST_FORMAT_G722' not handled in switch
app_transcoder.c:1509: warning: enumeration value 'AST_FORMAT_SIREN7' not handled in switch
app_transcoder.c:1509: warning: enumeration value 'AST_FORMAT_SIREN14' not handled in switch
app_transcoder.c:1509: warning: enumeration value 'AST_FORMAT_G719' not handled in switch
app_transcoder.c:1509: warning: enumeration value 'AST_FORMAT_SPEEX16' not handled in switch
app_transcoder.c:1509: warning: enumeration value 'AST_FORMAT_TESTLAW' not handled in switch
app_transcoder.c:1509: warning: enumeration value 'AST_FORMAT_SILK' not handled in switch
app_transcoder.c:1509: warning: enumeration value 'AST_FORMAT_SLINEAR' not handled in switch
app_transcoder.c:1509: warning: enumeration value 'AST_FORMAT_SLINEAR12' not handled in switch
app_transcoder.c:1509: warning: enumeration value 'AST_FORMAT_SLINEAR16' not handled in switch
app_transcoder.c:1509: warning: enumeration value 'AST_FORMAT_SLINEAR24' not handled in switch
app_transcoder.c:1509: warning: enumeration value 'AST_FORMAT_SLINEAR32' not handled in switch
app_transcoder.c:1509: warning: enumeration value 'AST_FORMAT_SLINEAR44' not handled in switch
app_transcoder.c:1509: warning: enumeration value 'AST_FORMAT_SLINEAR48' not handled in switch
app_transcoder.c:1509: warning: enumeration value 'AST_FORMAT_SLINEAR96' not handled in switch
app_transcoder.c:1509: warning: enumeration value 'AST_FORMAT_SLINEAR192' not handled in switch
app_transcoder.c:1509: warning: enumeration value 'AST_FORMAT_SPEEX32' not handled in switch
app_transcoder.c:1509: warning: enumeration value 'AST_FORMAT_CELT' not handled in switch
app_transcoder.c:1509: warning: enumeration value 'AST_FORMAT_H261' not handled in switch
app_transcoder.c:1509: warning: enumeration value 'AST_FORMAT_H263' not handled in switch
app_transcoder.c:1509: warning: enumeration value 'AST_FORMAT_H263_PLUS' not handled in switch
app_transcoder.c:1509: warning: enumeration value 'AST_FORMAT_H264' not handled in switch
app_transcoder.c:1509: warning: enumeration value 'AST_FORMAT_MP4_VIDEO' not handled in switch
app_transcoder.c:1509: warning: enumeration value 'AST_FORMAT_JPEG' not handled in switch
app_transcoder.c:1509: warning: enumeration value 'AST_FORMAT_PNG' not handled in switch
app_transcoder.c:1509: warning: enumeration value 'AST_FORMAT_T140RED' not handled in switch
app_transcoder.c:1509: warning: enumeration value 'AST_FORMAT_T140' not handled in switch
app_transcoder.c:1510: warning: case value '3' not in enumerated type 'enum ast_format_id'
app_transcoder.c:1521: warning: case value '4' not in enumerated type 'enum ast_format_id'
app_transcoder.c:1512: warning: case value '5' not in enumerated type 'enum ast_format_id'
app_transcoder.c:1513: warning: case value '8' not in enumerated type 'enum ast_format_id'
app_transcoder.c:1532: warning: enumeration value 'AST_FORMAT_G723_1' not handled in switch
app_transcoder.c:1532: warning: enumeration value 'AST_FORMAT_GSM' not handled in switch
app_transcoder.c:1532: warning: enumeration value 'AST_FORMAT_ULAW' not handled in switch
app_transcoder.c:1532: warning: enumeration value 'AST_FORMAT_ALAW' not handled in switch
app_transcoder.c:1532: warning: enumeration value 'AST_FORMAT_G726_AAL2' not handled in switch
app_transcoder.c:1532: warning: enumeration value 'AST_FORMAT_ADPCM' not handled in switch
app_transcoder.c:1532: warning: enumeration value 'AST_FORMAT_LPC10' not handled in switch
app_transcoder.c:1532: warning: enumeration value 'AST_FORMAT_G729A' not handled in switch
app_transcoder.c:1532: warning: enumeration value 'AST_FORMAT_SPEEX' not handled in switch
app_transcoder.c:1532: warning: enumeration value 'AST_FORMAT_ILBC' not handled in switch
app_transcoder.c:1532: warning: enumeration value 'AST_FORMAT_G726' not handled in switch
app_transcoder.c:1532: warning: enumeration value 'AST_FORMAT_G722' not handled in switch
app_transcoder.c:1532: warning: enumeration value 'AST_FORMAT_SIREN7' not handled in switch
app_transcoder.c:1532: warning: enumeration value 'AST_FORMAT_SIREN14' not handled in switch
app_transcoder.c:1532: warning: enumeration value 'AST_FORMAT_G719' not handled in switch
app_transcoder.c:1532: warning: enumeration value 'AST_FORMAT_SPEEX16' not handled in switch
app_transcoder.c:1532: warning: enumeration value 'AST_FORMAT_TESTLAW' not handled in switch
app_transcoder.c:1532: warning: enumeration value 'AST_FORMAT_SILK' not handled in switch
app_transcoder.c:1532: warning: enumeration value 'AST_FORMAT_SLINEAR' not handled in switch
app_transcoder.c:1532: warning: enumeration value 'AST_FORMAT_SLINEAR12' not handled in switch
app_transcoder.c:1532: warning: enumeration value 'AST_FORMAT_SLINEAR16' not handled in switch
app_transcoder.c:1532: warning: enumeration value 'AST_FORMAT_SLINEAR24' not handled in switch
app_transcoder.c:1532: warning: enumeration value 'AST_FORMAT_SLINEAR32' not handled in switch
app_transcoder.c:1532: warning: enumeration value 'AST_FORMAT_SLINEAR44' not handled in switch
app_transcoder.c:1532: warning: enumeration value 'AST_FORMAT_SLINEAR48' not handled in switch
app_transcoder.c:1532: warning: enumeration value 'AST_FORMAT_SLINEAR96' not handled in switch
app_transcoder.c:1532: warning: enumeration value 'AST_FORMAT_SLINEAR192' not handled in switch
app_transcoder.c:1532: warning: enumeration value 'AST_FORMAT_SPEEX32' not handled in switch
app_transcoder.c:1532: warning: enumeration value 'AST_FORMAT_CELT' not handled in switch
app_transcoder.c:1532: warning: enumeration value 'AST_FORMAT_H261' not handled in switch
app_transcoder.c:1532: warning: enumeration value 'AST_FORMAT_H263' not handled in switch
app_transcoder.c:1532: warning: enumeration value 'AST_FORMAT_H263_PLUS' not handled in switch
app_transcoder.c:1532: warning: enumeration value 'AST_FORMAT_H264' not handled in switch
app_transcoder.c:1532: warning: enumeration value 'AST_FORMAT_MP4_VIDEO' not handled in switch
app_transcoder.c:1532: warning: enumeration value 'AST_FORMAT_JPEG' not handled in switch
app_transcoder.c:1532: warning: enumeration value 'AST_FORMAT_PNG' not handled in switch
app_transcoder.c:1532: warning: enumeration value 'AST_FORMAT_T140RED' not handled in switch
app_transcoder.c:1532: warning: enumeration value 'AST_FORMAT_T140' not handled in switch
app_transcoder.c:1534: warning: case value '1' not in enumerated type 'enum ast_format_id'
make[1]: *** [app_transcoder.o] Error 1
make: *** [apps] Error 2
```

I also test ffmoeg 0.6.5 version.
It's only fix follow error message.

```
app_transcoder.c:520: warning: 'sws_getContext' is deprecated (declared at /usr/local/include/libswscale/swscale.h:194)
```

Could help fix error message?Thanks a lot.

**Comment by marcelloceschia** [comment]
I will check this later today (UTC+1) or tomorrow

**Comment by marcelloceschia** [comment]
@akong77 

I think you did no used this version.

**Comment by akong77** [comment]
Is this app_transcoder version have not compile to asterisk 11?Or have any bug?

**Comment by marcelloceschia** [comment]
this version is for asterisk 11! But you have to check if all functions work - I only converted the source to asterisk 11 api

**Comment by akong77** [comment]
I can tell you my system.
Centos 5.9 x86
Asterisk 11.6
ffmpeg 0.6.5 (yum)
Could you tell me app_transcoder need some application and what version?
I will check it.

**Comment by marcelloceschia** [comment]
cmake >= 2.6
asterisk 11
avcodec >= 51

so please downlod this version, compile it using the instruction in README and test it

**Comment by akong77** [comment]
Hello,
I check some app version.
[root@220-128-142-99 src]# cmake --help
cmake version 2.6-patch 4

asterisk 11

[root@220-128-142-99 src]# ffmpeg
FFmpeg version 0.6.5, Copyright (c) 2000-2010 the FFmpeg developers
  built on Jan 29 2012 23:56:18 with gcc 4.1.2 20080704 (Red Hat 4.1.2-51)
  configuration: --prefix=/usr --libdir=/usr/lib --shlibdir=/usr/lib --mandir=/usr/share/man --incdir=/usr/include --disable-avisynth --extra-cflags='-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m32 -march=i386 -mtune=generic -fasynchronous-unwind-tables' --enable-avfilter --enable-avfilter-lavf --enable-libdirac --enable-libfaac --enable-libfaad --enable-libfaadbin --enable-libgsm --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libx264 --enable-gpl --enable-nonfree --enable-postproc --enable-pthreads --enable-shared --enable-swscale --enable-vdpau --enable-version3 --enable-x11grab
  libavutil     50.15. 1 / 50.15. 1
  libavcodec    52.72. 2 / 52.72. 2
  libavformat   52.64. 2 / 52.64. 2
  libavdevice   52. 2. 0 / 52. 2. 0
  libavfilter    1.19. 0 /  1.19. 0
  libswscale     0.11. 0 /  0.11. 0
  libpostproc   51. 2. 0 / 51. 2. 0

I compile app_transcoder.c for asterisk 11 version.But still get some error.It's reference README.The app_transocder.c use newer.

/usr/local/src/app_transcoder-master/app_transcoder.c: In function 'VideoTranscoderCreate':
/usr/local/src/app_transcoder-master/app_transcoder.c:722: error: 'AVDictionary' undeclared (first use in this function)
/usr/local/src/app_transcoder-master/app_transcoder.c:722: error: (Each undeclared identifier is reported only once
/usr/local/src/app_transcoder-master/app_transcoder.c:722: error: for each function it appears in.)
/usr/local/src/app_transcoder-master/app_transcoder.c:722: error: 'options' undeclared (first use in this function)
/usr/local/src/app_transcoder-master/app_transcoder.c:825: warning: assignment makes pointer from integer without a cast
/usr/local/src/app_transcoder-master/app_transcoder.c:826: warning: assignment makes pointer from integer without a cast
/usr/local/src/app_transcoder-master/app_transcoder.c:840: warning: assignment makes pointer from integer without a cast
/usr/local/src/app_transcoder-master/app_transcoder.c:841: warning: assignment makes pointer from integer without a cast
make[2]: **\* [CMakeFiles/app_transcoder.dir/app_transcoder.c.o] Error 1
make[1]: **\* [CMakeFiles/app_transcoder.dir/all] Error 2
make: **\* [all] Error 2

If I copy app_transcoder.c to asterisk 11.6/apps and make it.

[root@220-128-142-99 asterisk-11.6.0]# make
   [CC] app_transcoder.c -> app_transcoder.o
app_transcoder.c: In function 'SendH263VideoFrame':
app_transcoder.c:169: warning: unused variable 'astFormat'
app_transcoder.c:168: warning: unused variable 'size'
app_transcoder.c: In function 'VideoTranscoderCreate':
app_transcoder.c:722: error: 'AVDictionary' undeclared (first use in this function)
app_transcoder.c:722: error: (Each undeclared identifier is reported only once
app_transcoder.c:722: error: for each function it appears in.)
app_transcoder.c:722: error: 'options' undeclared (first use in this function)
app_transcoder.c:825: warning: implicit declaration of function 'avcodec_alloc_context3'
app_transcoder.c:825: warning: assignment makes pointer from integer without a cast
app_transcoder.c:826: warning: assignment makes pointer from integer without a cast
app_transcoder.c:840: warning: assignment makes pointer from integer without a cast
app_transcoder.c:841: warning: assignment makes pointer from integer without a cast
app_transcoder.c:921: warning: implicit declaration of function 'avcodec_open2'
app_transcoder.c: In function 'rfc2190_append':
app_transcoder.c:1048: warning: dereferencing type-punned pointer will break strict-aliasing rules
app_transcoder.c: In function 'rfc2429_append':
app_transcoder.c:1100: warning: unused variable 'pebit'
app_transcoder.c: In function 'app_transcode':
app_transcoder.c:1509: warning: enumeration value 'AST_FORMAT_G723_1' not handled in switch
app_transcoder.c:1509: warning: enumeration value 'AST_FORMAT_GSM' not handled in switch
app_transcoder.c:1509: warning: enumeration value 'AST_FORMAT_ULAW' not handled in switch
app_transcoder.c:1509: warning: enumeration value 'AST_FORMAT_ALAW' not handled in switch
app_transcoder.c:1509: warning: enumeration value 'AST_FORMAT_G726_AAL2' not handled in switch
app_transcoder.c:1509: warning: enumeration value 'AST_FORMAT_ADPCM' not handled in switch
app_transcoder.c:1509: warning: enumeration value 'AST_FORMAT_LPC10' not handled in switch
app_transcoder.c:1509: warning: enumeration value 'AST_FORMAT_G729A' not handled in switch
app_transcoder.c:1509: warning: enumeration value 'AST_FORMAT_SPEEX' not handled in switch
app_transcoder.c:1509: warning: enumeration value 'AST_FORMAT_ILBC' not handled in switch
app_transcoder.c:1509: warning: enumeration value 'AST_FORMAT_G726' not handled in switch
app_transcoder.c:1509: warning: enumeration value 'AST_FORMAT_G722' not handled in switch
app_transcoder.c:1509: warning: enumeration value 'AST_FORMAT_SIREN7' not handled in switch
app_transcoder.c:1509: warning: enumeration value 'AST_FORMAT_SIREN14' not handled in switch
app_transcoder.c:1509: warning: enumeration value 'AST_FORMAT_G719' not handled in switch
app_transcoder.c:1509: warning: enumeration value 'AST_FORMAT_SPEEX16' not handled in switch
app_transcoder.c:1509: warning: enumeration value 'AST_FORMAT_TESTLAW' not handled in switch
app_transcoder.c:1509: warning: enumeration value 'AST_FORMAT_SILK' not handled in switch
app_transcoder.c:1509: warning: enumeration value 'AST_FORMAT_SLINEAR' not handled in switch
app_transcoder.c:1509: warning: enumeration value 'AST_FORMAT_SLINEAR12' not handled in switch
app_transcoder.c:1509: warning: enumeration value 'AST_FORMAT_SLINEAR16' not handled in switch
app_transcoder.c:1509: warning: enumeration value 'AST_FORMAT_SLINEAR24' not handled in switch
app_transcoder.c:1509: warning: enumeration value 'AST_FORMAT_SLINEAR32' not handled in switch
app_transcoder.c:1509: warning: enumeration value 'AST_FORMAT_SLINEAR44' not handled in switch
app_transcoder.c:1509: warning: enumeration value 'AST_FORMAT_SLINEAR48' not handled in switch
app_transcoder.c:1509: warning: enumeration value 'AST_FORMAT_SLINEAR96' not handled in switch
app_transcoder.c:1509: warning: enumeration value 'AST_FORMAT_SLINEAR192' not handled in switch
app_transcoder.c:1509: warning: enumeration value 'AST_FORMAT_SPEEX32' not handled in switch
app_transcoder.c:1509: warning: enumeration value 'AST_FORMAT_CELT' not handled in switch
app_transcoder.c:1509: warning: enumeration value 'AST_FORMAT_H261' not handled in switch
app_transcoder.c:1509: warning: enumeration value 'AST_FORMAT_H263' not handled in switch
app_transcoder.c:1509: warning: enumeration value 'AST_FORMAT_H263_PLUS' not handled in switch
app_transcoder.c:1509: warning: enumeration value 'AST_FORMAT_H264' not handled in switch
app_transcoder.c:1509: warning: enumeration value 'AST_FORMAT_MP4_VIDEO' not handled in switch
app_transcoder.c:1509: warning: enumeration value 'AST_FORMAT_JPEG' not handled in switch
app_transcoder.c:1509: warning: enumeration value 'AST_FORMAT_PNG' not handled in switch
app_transcoder.c:1509: warning: enumeration value 'AST_FORMAT_T140RED' not handled in switch
app_transcoder.c:1509: warning: enumeration value 'AST_FORMAT_T140' not handled in switch
app_transcoder.c:1510: warning: case value '3' not in enumerated type 'enum ast_format_id'
app_transcoder.c:1521: warning: case value '4' not in enumerated type 'enum ast_format_id'
app_transcoder.c:1512: warning: case value '5' not in enumerated type 'enum ast_format_id'
app_transcoder.c:1513: warning: case value '8' not in enumerated type 'enum ast_format_id'
app_transcoder.c:1532: warning: enumeration value 'AST_FORMAT_G723_1' not handled in switch
app_transcoder.c:1532: warning: enumeration value 'AST_FORMAT_GSM' not handled in switch
app_transcoder.c:1532: warning: enumeration value 'AST_FORMAT_ULAW' not handled in switch
app_transcoder.c:1532: warning: enumeration value 'AST_FORMAT_ALAW' not handled in switch
app_transcoder.c:1532: warning: enumeration value 'AST_FORMAT_G726_AAL2' not handled in switch
app_transcoder.c:1532: warning: enumeration value 'AST_FORMAT_ADPCM' not handled in switch
app_transcoder.c:1532: warning: enumeration value 'AST_FORMAT_LPC10' not handled in switch
app_transcoder.c:1532: warning: enumeration value 'AST_FORMAT_G729A' not handled in switch
app_transcoder.c:1532: warning: enumeration value 'AST_FORMAT_SPEEX' not handled in switch
app_transcoder.c:1532: warning: enumeration value 'AST_FORMAT_ILBC' not handled in switch
app_transcoder.c:1532: warning: enumeration value 'AST_FORMAT_G726' not handled in switch
app_transcoder.c:1532: warning: enumeration value 'AST_FORMAT_G722' not handled in switch
app_transcoder.c:1532: warning: enumeration value 'AST_FORMAT_SIREN7' not handled in switch
app_transcoder.c:1532: warning: enumeration value 'AST_FORMAT_SIREN14' not handled in switch
app_transcoder.c:1532: warning: enumeration value 'AST_FORMAT_G719' not handled in switch
app_transcoder.c:1532: warning: enumeration value 'AST_FORMAT_SPEEX16' not handled in switch
app_transcoder.c:1532: warning: enumeration value 'AST_FORMAT_TESTLAW' not handled in switch
app_transcoder.c:1532: warning: enumeration value 'AST_FORMAT_SILK' not handled in switch
app_transcoder.c:1532: warning: enumeration value 'AST_FORMAT_SLINEAR' not handled in switch
app_transcoder.c:1532: warning: enumeration value 'AST_FORMAT_SLINEAR12' not handled in switch
app_transcoder.c:1532: warning: enumeration value 'AST_FORMAT_SLINEAR16' not handled in switch
app_transcoder.c:1532: warning: enumeration value 'AST_FORMAT_SLINEAR24' not handled in switch
app_transcoder.c:1532: warning: enumeration value 'AST_FORMAT_SLINEAR32' not handled in switch
app_transcoder.c:1532: warning: enumeration value 'AST_FORMAT_SLINEAR44' not handled in switch
app_transcoder.c:1532: warning: enumeration value 'AST_FORMAT_SLINEAR48' not handled in switch
app_transcoder.c:1532: warning: enumeration value 'AST_FORMAT_SLINEAR96' not handled in switch
app_transcoder.c:1532: warning: enumeration value 'AST_FORMAT_SLINEAR192' not handled in switch
app_transcoder.c:1532: warning: enumeration value 'AST_FORMAT_SPEEX32' not handled in switch
app_transcoder.c:1532: warning: enumeration value 'AST_FORMAT_CELT' not handled in switch
app_transcoder.c:1532: warning: enumeration value 'AST_FORMAT_H261' not handled in switch
app_transcoder.c:1532: warning: enumeration value 'AST_FORMAT_H263' not handled in switch
app_transcoder.c:1532: warning: enumeration value 'AST_FORMAT_H263_PLUS' not handled in switch
app_transcoder.c:1532: warning: enumeration value 'AST_FORMAT_H264' not handled in switch
app_transcoder.c:1532: warning: enumeration value 'AST_FORMAT_MP4_VIDEO' not handled in switch
app_transcoder.c:1532: warning: enumeration value 'AST_FORMAT_JPEG' not handled in switch
app_transcoder.c:1532: warning: enumeration value 'AST_FORMAT_PNG' not handled in switch
app_transcoder.c:1532: warning: enumeration value 'AST_FORMAT_T140RED' not handled in switch
app_transcoder.c:1532: warning: enumeration value 'AST_FORMAT_T140' not handled in switch
app_transcoder.c:1534: warning: case value '1' not in enumerated type 'enum ast_format_id'
make[1]: **\* [app_transcoder.o] Error 1
make: **\* [apps] Error 2

Am I lost install any application?

**Comment by marcelloceschia** [comment]
```
ffmpeg -version

ffmpeg version 2.1.1
built on Nov 27 2013 18:31:36 with gcc 4.8 (SUSE Linux)
configuration: --shlibdir=/usr/lib --prefix=/usr --mandir=/usr/share/man --libdir=/usr/lib --enable-shared --disable-static --enable-debug --disable-stripping --extra-cflags='-fomit-frame-pointer -fmessage-length=0 -grecord-gcc-switches -fstack-protector -O2 -Wall -D_FORTIFY_SOURCE=2 -funwind-tables -fasynchronous-unwind-tables -g -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -I/usr/include/gsm' --enable-gpl --enable-x11grab --enable-version3 --enable-pthreads --enable-avfilter --enable-libpulse --enable-libvpx --enable-libopus --enable-libass --enable-libmp3lame --enable-libvorbis --enable-libtheora --enable-libspeex --enable-libxvid --enable-libx264 --enable-libschroedinger --enable-libgsm --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-postproc --enable-libdc1394 --enable-librtmp --enable-libfreetype --enable-avresample --enable-libtwolame --enable-libvo-aacenc --enable-gnutls
libavutil      52. 48.101 / 52. 48.101
libavcodec     55. 39.101 / 55. 39.101
libavformat    55. 19.104 / 55. 19.104
libavdevice    55.  5.100 / 55.  5.100
libavfilter     3. 90.100 /  3. 90.100
libavresample   1.  1.  0 /  1.  1.  0
libswscale      2.  5.101 /  2.  5.101
libswresample   0. 17.104 /  0. 17.104
libpostproc    52.  3.100 / 52.  3.100
```

```
# mkdir build
# cd build
# cmake ..

-- The C compiler identification is GNU 4.8.1
-- The CXX compiler identification is GNU 4.8.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Configuring done
-- Generating done
-- Build files have been written to: /usr/local/src/asterisk/asterisk-11/app_transcoder/build

# make
Scanning dependencies of target app_transcoder
[100%] Building C object CMakeFiles/app_transcoder.dir/app_transcoder.c.o
/usr/local/src/asterisk/asterisk-11/app_transcoder/app_transcoder.c: In function ‘VideoTranscoderEncode’:
/usr/local/src/asterisk/asterisk-11/app_transcoder/app_transcoder.c:629:4: warning: ‘avcodec_encode_video’ is deprecated (declared at /usr/include/libavcodec/avcodec.h:4260) [-Wdeprecated-declarations]
    vtc->bufferLen = avcodec_encode_video(vtc->encoderCtx, vtc->buffer, vtc->bufferSize, vtc->encoderPic);
    ^
Linking C shared library app_transcoder.so
```

**Comment by akong77** [comment]
Hello,I compile success.So,It's must ffmpeg version >=2.0.2

**Comment by marcelloceschia** [comment]
using the latest version is never a bad idea.
